feat(front-end): implement empty pages for all examples

diff --git a/.github/workflows/feature-branch-build.yml b/.github/workflows/feature-branch-build.yml
--- a/.github/workflows/feature-branch-build.yml
+++ b/.github/workflows/feature-branch-build.yml
@@ -50,26 +50,26 @@ jobs:
           aws-region: eu-west-1
           role-to-assume: ${{ vars.AWS_AUTH_ROLE }}
 
-#      - name: Publish web-app to S3
-#        shell: bash {0}
-#        run: |
-#          set -e
-#          aws s3 rm --recursive s3://${{ env.S3_HOSTING_BUCKET }}/${{ env.SAFE_SOURCE_NAME }}/
-#          aws s3 sync ./front-end/out/ s3://${{ env.S3_HOSTING_BUCKET }}/${{ env.SAFE_SOURCE_NAME }}
-#
-#      - name: Invalidate CF distribution cache
-#        shell: bash
-#        run: |
-#          DISTRIBUTION_ID=$(aws cloudfront list-distributions \
-#          | jq -r '.DistributionList.Items | map(select(.Comment | contains("${{ env.CF_DISTRIBUTION_NAME }}")).Id) | .[0]')
-#
-#          echo "Triggering invalidation for alias and version tag environments"
-#          INVALIDATION=$(aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*")
-#          echo "Invalidation request: $INVALIDATION"
-#
-#          WAIT=${{ env.CF_INVALIDATION_WAIT }}
-#          [ "$WAIT" != true ] && echo "Skipping waiting for invalidation completion" && exit 0
-#
-#          echo "Waiting for invalidation completion..."
-#          INVALIDATION_ID=$(echo "$INVALIDATION" | jq -r '.Invalidation.Id')
-#          aws cloudfront wait invalidation-completed --distribution-id "$DISTRIBUTION_ID" --id "$INVALIDATION_ID"
+      - name: Publish web-app to S3
+        shell: bash {0}
+        run: |
+          set -e
+          aws s3 rm --recursive s3://${{ env.S3_HOSTING_BUCKET }}/${{ env.SAFE_SOURCE_NAME }}/
+          aws s3 sync ./front-end/out/ s3://${{ env.S3_HOSTING_BUCKET }}/${{ env.SAFE_SOURCE_NAME }}
+
+      - name: Invalidate CF distribution cache
+        shell: bash
+        run: |
+          DISTRIBUTION_ID=$(aws cloudfront list-distributions \
+          | jq -r '.DistributionList.Items | map(select(.Comment | contains("${{ env.CF_DISTRIBUTION_NAME }}")).Id) | .[0]')
+
+          echo "Triggering invalidation for alias and version tag environments"
+          INVALIDATION=$(aws cloudfront create-invalidation --distribution-id "$DISTRIBUTION_ID" --paths "/*")
+          echo "Invalidation request: $INVALIDATION"
+
+          WAIT=${{ env.CF_INVALIDATION_WAIT }}
+          [ "$WAIT" != true ] && echo "Skipping waiting for invalidation completion" && exit 0
+
+          echo "Waiting for invalidation completion..."
+          INVALIDATION_ID=$(echo "$INVALIDATION" | jq -r '.Invalidation.Id')
+          aws cloudfront wait invalidation-completed --distribution-id "$DISTRIBUTION_ID" --id "$INVALIDATION_ID"
